Add tcp and udp moudule Integration tests and BBE
ballerina-platform/ballerina-distribution pull request #1142
Opened 2021-01-19 08:43 UTC by MohamedSabthar

## Purpose
> Add tcp and udp moudule Integration tests and BBE

2021-01-19 09:37 UTC, Maninda commented on examples/tcp-listener/tcp_listener.bal
> +}
```suggestion
}

```

2021-01-19 09:37 UTC, Maninda commented on stdlib-integration-tests/udp/tests/udp_tests.bal
> +    return returnStr;
```suggestion
    return returnStr;
    
```

2021-01-19 09:38 UTC, Maninda commented on stdlib-integration-tests/udp/tests/udp_tests.bal
> +}
```suggestion
}

```

2021-01-19 10:37 UTC, MohamedSabthar commented on examples/tcp-listener/tcp_listener.bal
> +}
added new line

2021-01-19 10:37 UTC, MohamedSabthar commented on stdlib-integration-tests/udp/tests/udp_tests.bal
> +}
added new line

2021-01-19 16:26 UTC, praneesha commented on examples/tcp-client/tcp_client.bal
> +// This is the client implementation for the TCP socket.
```suggestion
// This is the client implementation of the TCP socket.
```

2021-01-19 16:26 UTC, praneesha commented on examples/tcp-listener/tcp_listener.bal
> +    // if it happens during the `onConnect` and `onBytes`.
```suggestion
    // if it happens during the `onConnect` and `onBytes` methods.
```

2021-01-19 16:26 UTC, praneesha commented on examples/tcp-listener/tcp_listener.description
>  // The TCP Listener is used to expose TCP service over the TCP protocol.
```suggestion
// The TCP Listener is used to expose a TCP service over the TCP protocol.
```

2021-01-19 16:26 UTC, praneesha commented on examples/udp-connect-client/udp_connect_client.bal
> +// This is the connection oriented client implementation for the UDP socket.
```suggestion
// This is the connection-oriented client implementation of the UDP socket.
```

2021-01-19 16:26 UTC, praneesha commented on examples/udp-listener/udp_listener.bal
> +    // You may replace the onBytes method with onDatagram which reads the data as
```suggestion
    // You may replace the `onBytes` method with `onDatagram`, which reads the data as
```

2021-01-20 03:47 UTC, MohamedSabthar commented on examples/tcp-client/tcp_client.bal
> +// This is the client implementation for the TCP socket.
removed

2021-01-20 03:47 UTC, MohamedSabthar commented on examples/tcp-client/tcp_client.bal
> +
removed

2021-01-20 03:51 UTC, MohamedSabthar commented on examples/tcp-client/tcp_client.out
>  # `.bal` file and use the `ballerina run` command below.
fixed in udp,tcp examples

2021-01-20 03:51 UTC, MohamedSabthar commented on examples/tcp-listener/tcp_listener.bal
> +// This is the server implementation for the TCP socket.
removed

2021-01-20 03:51 UTC, MohamedSabthar commented on examples/udp-client/udp_client.bal
> +    // Send the data to remote host.
updated

2021-01-20 03:52 UTC, MohamedSabthar commented on examples/tcp-client/tcp_client.bal
> +// This is the client implementation for the TCP socket.
updated

2021-01-20 03:54 UTC, MohamedSabthar commented on examples/tcp-listener/tcp_listener.bal
> +    // if it happens during the `onConnect` and `onBytes`.
updated

2021-01-20 03:55 UTC, MohamedSabthar commented on examples/udp-connect-client/udp_connect_client.bal
> +// This is the connection oriented client implementation for the UDP socket.
updated

2021-01-20 03:55 UTC, MohamedSabthar commented on examples/tcp-listener/tcp_listener.description
>  // The TCP Listener is used to expose TCP service over the TCP protocol.
updated

2021-01-20 03:56 UTC, MohamedSabthar commented on examples/udp-listener/udp_listener.bal
> +    // You may replace the onBytes method with onDatagram which reads the data as
updated

2021-01-20 04:02 UTC, MohamedSabthar commented on examples/tcp-listener/tcp_listener.out
> +Client left: 48735
new line added

2021-01-20 04:40 UTC, ThisaruGuruge commented
Shall we resolve the conflicts, so that we can merge this?
@MohamedSabthar @Maninda @praneesha

2021-01-20 04:45 UTC, lafernando commented
Is this PR #1140 having the same changes as here? Please check #1140 for related comments.

2021-01-20 04:47 UTC, lafernando requested changes
Please check and do the same changes as mentioned in the comments in #1140.

2021-01-20 05:16 UTC, MohamedSabthar commented
> Please check and do the same changes as mentioned in the comments in #1140.

changes made according to the review.

2021-01-20 05:48 UTC, lafernando commented
@MohamedSabthar There are some more comments there in #1140 that you haven't replied to, please check them as well.

2021-01-20 05:57 UTC, MohamedSabthar commented
> @MohamedSabthar There are some more comments there in #1140 that you haven't replied to, please check them as well.

made the changes and replied now.

2021-01-20 07:23 UTC, praneesha approved these changes

2021-01-20 10:42 UTC, MohamedSabthar commented
Duplicate of #https://github.com/ballerina-platform/ballerina-distribution/pull/1140

2021-01-20 14:57 UTC, Maninda commented
Mistakenly opened. Will close it.

2021-01-20 14:57 UTC, closed without merging