Split the BBE, send-and-receive-emails into three BBEs for clarity
ballerina-platform/ballerina-distribution pull request #1289
Opened 2021-02-11 08:43 UTC by Maninda

Split the BBE, `send-and-receive-emails` into the following 3 BBEs.
1. send-email
2. receive-email-using-client
3. receive-email-using-listener

2021-02-11 09:19 UTC, lafernando requested changes

2021-02-11 09:19 UTC, lafernando commented on examples/receive-email-using-client/receive_email_using_client.bal
> +
Remove extra line.

2021-02-11 09:19 UTC, lafernando commented on examples/receive-email-using-client/receive_email_using_client.bal
> +
Remove extra line.

2021-02-11 09:19 UTC, lafernando commented on examples/receive-email-using-client/receive_email_using_client.description
> +// The Email Connector is used to receive (with POP3 or IMAP4) emails
Shall we say "The email client" ..

2021-02-11 09:19 UTC, lafernando commented on examples/receive-email-using-listener/receive_email_using_listener.description
> +// The Email Connector is used to receive (with POP3 or IMAP4) emails
Shall we say "The email listener" ..

2021-02-11 09:23 UTC, praneesha commented on examples/receive-email-using-client/receive_email_using_client.description
> +// emails with default configurations over SSL using default
```suggestion
// emails with default configurations over SSL using the default
```

2021-02-11 09:23 UTC, praneesha commented on examples/receive-email-using-client/receive_email_using_client.metatags
> +description: This is a BBE on receiving emails. It has client functionality for email receiving.
```suggestion
description: This is a BBE on receiving emails. It has the client functionality for receiving emails.
```

2021-02-11 09:23 UTC, praneesha commented on examples/receive-email-using-listener/receive_email_using_listener.description
> +// default ports.<br/><br/>
```suggestion
// the default ports.<br/><br/>
```

2021-02-11 09:23 UTC, praneesha commented on examples/receive-email-using-listener/receive_email_using_listener.metatags
> +description: This is a BBE on receiving emails. It has a listener based functionality for receiving emails.
```suggestion
description: This BBE is about receiving emails. It has a listener-based functionality for receiving emails.
```

2021-02-11 09:23 UTC, praneesha commented on examples/send-email/send_email.bal
> +        // List of recipients when replying to the email is added as follows.
```suggestion
        // List of recipients when replying to the email are added as follows.
```

2021-02-11 09:23 UTC, praneesha commented on examples/send-email/send_email.description
> +// over SSL using default ports.<br/><br/>
```suggestion
// over SSL using the default ports.<br/><br/>
```

2021-02-11 09:23 UTC, praneesha commented on examples/send-email/send_email.metatags
> +description: This is a BBE on sending emails.
```suggestion
description: This BBE is about sending emails.
```

2021-02-11 10:43 UTC, praneesha approved these changes

2021-02-11 10:45 UTC, Maninda commented on examples/receive-email-using-client/receive_email_using_client.bal
> +
```suggestion
```

2021-02-11 10:46 UTC, Maninda commented on examples/receive-email-using-client/receive_email_using_client.bal
> +
```suggestion
```

2021-02-11 10:46 UTC, Maninda commented on examples/receive-email-using-client/receive_email_using_client.description
> +// The Email Connector is used to receive (with POP3 or IMAP4) emails
```suggestion
// The email client is used to receive (with POP3 or IMAP4) emails
```

2021-02-11 10:47 UTC, Maninda commented on examples/receive-email-using-listener/receive_email_using_listener.description
> +// The Email Connector is used to receive (with POP3 or IMAP4) emails
```suggestion
// The email listener is used to receive (with POP3 or IMAP4) emails
```

2021-02-11 10:48 UTC, Maninda commented on examples/receive-email-using-client/receive_email_using_client.bal
> +
Removed.

2021-02-11 10:48 UTC, Maninda commented on examples/receive-email-using-client/receive_email_using_client.bal
> +
Removed.

2021-02-11 10:48 UTC, Maninda commented on examples/receive-email-using-client/receive_email_using_client.description
> +// The Email Connector is used to receive (with POP3 or IMAP4) emails
Changed.

2021-02-11 10:49 UTC, Maninda commented on examples/receive-email-using-listener/receive_email_using_listener.description
> +// The Email Connector is used to receive (with POP3 or IMAP4) emails
Changed.

2021-02-14 14:49 UTC, Maninda commented on examples/receive-email-using-client/receive_email_using_client.bal
> +        io:println("Email Body: ", emailResponse.body);
```suggestion
        io:println("Email Body: ", emailResponse?.body);
```

2021-02-14 14:49 UTC, Maninda commented on examples/receive-email-using-client/receive_email_using_client.bal
> +        io:println("Email Body: ", emailResponse.body);
```suggestion
        io:println("Email Body: ", emailResponse?.body);
```

2021-02-14 14:49 UTC, Maninda commented on examples/receive-email-using-listener/receive_email_using_listener.bal
> +        io:println("Email Body: ", emailMessage.body);
```suggestion
        io:println("Email Body: ", emailMessage?.body);
```

2021-02-14 15:22 UTC, lafernando approved these changes

2021-02-14 18:39 UTC, merged