Add ballerina version command
ballerina-platform/ballerina-distribution pull request #2401
Opened 2021-12-07 11:01 UTC by udda1996

## Purpose
Add bal -v command at the end of the postinstall to execute it for the first time.

2021-12-12 19:18 UTC, keizer619 approved these changes

2021-12-12 19:19 UTC, keizer619 requested changes
@udda1996 Shall we include this for other installers? If this issue happens in there as well

2021-12-15 06:48 UTC, udda1996 commented
> @udda1996 Shall we include this for other installers? If this issue happens in there as well

This issue not reproducible in Windows

2021-12-23 17:19 UTC, keizer619 approved these changes

2022-02-18 19:34 UTC, closed without merging