Make HTTP BBEs more RESTful
ballerina-platform/ballerina-distribution pull request #3292
Opened 2022-10-16 16:22 UTC by chamil321

## Purpose
> Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/3491

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2022-10-24 06:09 UTC, ayeshLK commented
In `examples/http-100-continue/http_100_continue.bal`:
- Shall we remove unwanted parenthesis in `if` conditions ?
```ballerina
if (request.expects100Continue()) {
    ...
}
```
- Shall we use mime-constants for media-types ?
```ballerina
if mediaType.toLowerAscii() == "text/plain" {
    ...
}
```

2022-10-24 07:17 UTC, manuranga commented on examples/dynamic-listener/dynamic_listener.bal
> +    resource function get shutdown(http:Caller caller) returns error? {
Should this be `get`, how about `post`?

2022-11-08 07:11 UTC, sameerajayasoma requested changes

2022-11-08 07:11 UTC, sameerajayasoma commented on examples/http-path-param/http_path_param.bal
> +    resource function get employee/[string id]() returns string {
Returning string doesn't sound like a good example here?

2022-11-08 07:11 UTC, sameerajayasoma commented on examples/http-client-endpoint/http_client_endpoint.bal
> +    json resp = check clientEndpoint->/get.get(test = 123);
This is confusing as the first HTTP client example.

2022-11-08 07:11 UTC, sameerajayasoma commented on examples/http-client-data-binding/http_client_data_binding.bal
> +        Person person = check backendClient->/backend/data;
Let's use a meaningful client name here.

2022-11-08 07:11 UTC, sameerajayasoma commented on examples/http-client-endpoint/http_client_endpoint.bal
>  public function main() returns error? {
Shouldn't we talk about both `fooClient->get("/foos")` and `fooClient->/ foos`?

2022-12-06 20:22 UTC, closed without merging