Add bbe for regexp langlib function usage
ballerina-platform/ballerina-distribution pull request #4189
Opened 2023-03-15 03:10 UTC by LakshanWeerasinghe

## Purpose
$subject

## Goals
> Fix: [issue](https://github.com/ballerina-platform/ballerina-lang/issues/39631)

2023-03-15 05:57 UTC, SasinduDilshara requested changes

2023-03-15 05:57 UTC, SasinduDilshara commented on examples/regexp-type-langlib-functions/regexp_langlib_functions.bal
> +    // Print the list of emails
print is a basic function in Ballerina, So we don't need this comment IMO, wdyt?

2023-03-15 05:57 UTC, SasinduDilshara commented on examples/regexp-type-langlib-functions/regexp_langlib_functions.bal
> +    string:RegExp validEmailPattern = re `[a-z]+@[a-z]+\.[a-z]+`;
Shall we use the original regex, instead of this one.
ex:- `([a-zA-Z0-9._%+-])+@([a-zA-Z0-9.-])+\.([a-zA-Z]{2,})`

2023-03-15 05:57 UTC, SasinduDilshara commented on examples/regexp-type-langlib-functions/regexp_langlib_functions.bal
> +    // Print the list of emails
```suggestion
    // Print the list of domains
```

2023-03-15 06:04 UTC, SasinduDilshara requested changes

2023-03-15 06:04 UTC, SasinduDilshara commented on examples/regexp-type-langlib-functions/regexp_langlib_functions.md
> +
Do we need this new line?

2023-03-15 06:04 UTC, SasinduDilshara commented on examples/regexp-type-langlib-functions/regexp_langlib_functions.metatags
> +keywords: ballerina, ballerina by example, bbe, regexp, RegExp, regex, regular expressions, ballerina regex functions
Shall we add something like `regexp langlib functions`.
wdyt?

2023-03-15 06:04 UTC, SasinduDilshara commented on examples/regexp-type-langlib-functions/regexp_langlib_functions.md
> +Ballerina supports a set of langlib functions to search and manipulate string values.
```suggestion
Ballerina supports a set of langlib functions for regular expressions to search and manipulate string values.
```

2023-03-15 06:13 UTC, SasinduDilshara requested changes

2023-03-15 06:13 UTC, SasinduDilshara commented on examples/regexp-type-langlib-functions/regexp_langlib_functions.bal
> +            regexp:Groups[] findAllGroups = emailGroupFindingPattern.findAllGroups(email);
```suggestion
            regexp:Groups[] emailGroups = emailGroupFindingPattern.findAllGroups(email);
```

2023-03-15 06:17 UTC, SasinduDilshara requested changes

2023-03-15 06:17 UTC, SasinduDilshara commented on examples/regexp-type-langlib-functions/regexp_langlib_functions.bal
> +    // Email group finding pattern
```suggestion
    // Email group finding pattern.
```
Check other places as well.

2023-03-15 08:14 UTC, LakshanWeerasinghe commented on examples/regexp-type-langlib-functions/regexp_langlib_functions.bal
> +            regexp:Groups[] findAllGroups = emailGroupFindingPattern.findAllGroups(email);
I'll change this to use `findGroups` function.

2023-03-15 08:18 UTC, LakshanWeerasinghe commented
@SasinduDilshara please refer #4194 for updated changes.

2023-03-20 03:06 UTC, LakshanWeerasinghe commented on examples/regexp-type-langlib-functions/regexp_langlib_functions.md
> +Ballerina supports a set of langlib functions to search and manipulate string values.
```suggestion
Ballerina ``RegExp`` type supports a set of langlib functions to search and manipulate string values.
```
This would be better.

2023-03-20 11:03 UTC, pcnfernando commented on examples/index.json
> +        "name": "RegExp type langlib functions",
Refactor the bbe as `RegExp operations`

2023-03-20 11:07 UTC, pcnfernando commented on examples/regexp-type-langlib-functions/regexp_type_langlib_functions.bal
> +    // Valid email pattern.
```suggestion
    // Define a RegExp pattern to match valid email addresses.
```

2023-03-20 11:08 UTC, pcnfernando commented on examples/regexp-type-langlib-functions/regexp_type_langlib_functions.bal
> +    string[] usernames = [];
```suggestion
    // Extract usernames and domains from valid email addresses.
    string[] usernames = [];
```

2023-03-20 11:09 UTC, pcnfernando commented on examples/regexp-type-langlib-functions/regexp_type_langlib_functions.bal
> +        // Check the email is a valid one.
```suggestion
        // Check if the email is valid.
```

2023-03-20 11:10 UTC, pcnfernando commented on examples/regexp-type-langlib-functions/regexp_type_langlib_functions.bal
> +        if isValidEmail {
```suggestion
        if validEmailPattern.isFullMatch(email) {
```

2023-03-20 11:10 UTC, pcnfernando commented on examples/regexp-type-langlib-functions/regexp_type_langlib_functions.bal
> +            // Finding usernames and domain names in a valid email.
```suggestion
            // Extract the username and domain from the email.
```

2023-03-20 11:15 UTC, pcnfernando commented on examples/regexp-type-langlib-functions/regexp_type_langlib_functions.md
> +Ballerina ``RegExp`` type supports a set of langlib functions to search and manipulate string values.
```suggestion
``RegExp`` type supports a set of langlib functions to search and manipulate string values.
```

2023-03-21 09:45 UTC, pcnfernando commented on examples/regexp-operations/regexp_operations.bal
> +
```suggestion
```

2023-03-23 02:57 UTC, praneesha commented on examples/regexp-operations/regexp_operations.bal
> +    // Split the comma separated email list.
```suggestion
    // Split the comma-separated email list.
```

2023-03-23 02:57 UTC, praneesha commented on examples/regexp-operations/regexp_operations.md
> +``RegExp`` type supports a set of langlib functions to search and manipulate string values.
```suggestion
The ``RegExp`` type supports a set of langlib functions to search and manipulate string values.
```

2023-03-27 07:27 UTC, pcnfernando commented on examples/regexp-operations/regexp_operations.bal
> +                usernames.push((<regexp:Span>emailGroups[1]).substring());
```suggestion
                // 0th element contains the entire match
                usernames.push((<regexp:Span>emailGroups[1]).substring());
```

2023-03-27 08:44 UTC, SasinduDilshara approved these changes

2023-03-27 09:05 UTC, merged