Add bbe for RegExp type
ballerina-platform/ballerina-distribution pull request #4190
Opened 2023-03-15 03:13 UTC by LakshanWeerasinghe

## Purpose
$subject

## Goals
>.  fix [issue](https://github.com/ballerina-platform/ballerina-lang/issues/39631)

2023-03-15 06:21 UTC, SasinduDilshara requested changes

2023-03-15 06:21 UTC, SasinduDilshara commented on examples/regexp-type/regexp.bal
> +    boolean result1 = re `a+`.isFullMatch("aaa");
```suggestion
    boolean result = re `a+`.isFullMatch("aaa");
```

2023-03-15 06:21 UTC, SasinduDilshara commented on examples/regexp-type/regexp.bal
> +    // Declare a RegExp using string module
```suggestion
    // Declare a RegExp using string module.
```

2023-03-15 06:21 UTC, SasinduDilshara commented on examples/regexp-type/regexp.metatags
> +keywords: ballerina, ballerina by example, bbe, regex, regexp, regular expression
Need a new line here.

2023-03-15 06:23 UTC, SasinduDilshara requested changes

2023-03-15 06:23 UTC, SasinduDilshara commented on examples/regexp-type/regexp.bal
> +    io:println("Pattern `(?i:BalleRINA)` matches xyz ", pattern6.isFullMatch("Ballerina"));
```suggestion
    io:println("Pattern `(?i:BalleRINA)` matches Ballerina ", pattern6.isFullMatch("Ballerina"));
```

2023-03-15 07:54 UTC, LakshanWeerasinghe commented
@SasinduDilshara please refer #4193 for updated changes

2023-03-16 06:27 UTC, SasinduDilshara commented
> @SasinduDilshara please refer #4193 for updated changes

Sure, Please cherrypick the relevant commits to here as well

2023-03-21 09:51 UTC, pcnfernando commented on examples/regexp-type/regexp_type.bal
> +    // Declare a RegExp using the string module.
```suggestion
    // Declare a RegExp using regular expression literal.
    // string module contains a type alias for Regexp type defined in regexp module
```

2023-03-21 09:52 UTC, pcnfernando commented on examples/regexp-type/regexp_type.bal
> +    // Declare a RegExp using the `fromString` method in the `lang.regexp` module.
```suggestion
    // Declare a RegExp using the `fromString` constructor method.
```

2023-03-21 09:54 UTC, pcnfernando commented on examples/regexp-type/regexp_type.bal
> +    boolean result = re `a+`.isFullMatch("aaa");
```suggestion
    // Matches any string that contains one or more consecutive "a" characters.
    boolean result = re `a+`.isFullMatch("aaa");
```

2023-03-21 09:55 UTC, pcnfernando commented on examples/regexp-type/regexp_type.bal
> +    string:RegExp pattern2 = re `abc|${literal}`;
```suggestion
    // Matches any string that starts with "abc" or "XYZ".
    string:RegExp pattern2 = re `abc|${literal}`;
```

2023-03-21 09:56 UTC, pcnfernando commented on examples/regexp-type/regexp_type.bal
> +    io:println("Pattern `abc|${\"xyz\"}` matches xyz ", pattern2.isFullMatch("xyz"));
```suggestion
    // Matches any string that starts with "abc" or "XYZ".
    io:println("Pattern `abc|${\"xyz\"}` matches xyz ", pattern2.isFullMatch("xyz"));
```

2023-03-21 09:57 UTC, pcnfernando commented on examples/regexp-type/regexp_type.bal
> +    // Ballerina RegExp supports writing Unicode general category patterns.
```suggestion
    // RegExp supports writing Unicode general category patterns. 
```

2023-03-21 09:58 UTC, pcnfernando commented on examples/regexp-type/regexp_type.bal
> +    // The `\p{...}` pattern is used.
```suggestion
```

2023-03-21 10:05 UTC, pcnfernando commented on examples/regexp-type/regexp_type.bal
> +    io:println("Pattern `\\p{Ll}` matches a ", pattern3.isFullMatch("a"));
```suggestion
    io:println("Pattern `\\p{Ll}` matches `a`: ", "a".matches(pattern3));
```

2023-03-21 10:06 UTC, pcnfernando commented on examples/regexp-type/regexp_type.out
> +Pattern `\p{Ll}` matches a true
```suggestion
Pattern `\p{Ll}` matches `a`: true
```

2023-03-21 10:12 UTC, pcnfernando commented on examples/regexp-type/regexp_type.bal
> +    io:println("Pattern `\\p{P}` matches 0 ", pattern4.isFullMatch("0"));
Update as https://github.com/ballerina-platform/ballerina-distribution/pull/4190/files#r1143139666

2023-03-21 10:12 UTC, pcnfernando commented on examples/regexp-type/regexp_type.bal
> +    // The `\p{sc=...}` pattern is used.
```suggestion
```

2023-03-21 10:13 UTC, pcnfernando commented on examples/regexp-type/regexp_type.bal
> +    // Ballerina RegExp supports writing different Unicode languages using Unicode script patterns.
```suggestion
    // RegExp supports writing different Unicode languages using Unicode script patterns.
```

2023-03-21 10:19 UTC, pcnfernando commented on examples/regexp-type/regexp_type.bal
> +    io:println("Pattern `\\p{sc=Latin}` matches aεЛ ", latinValue is regexp:Span);
Print the actual substring from the Span

2023-03-21 10:20 UTC, pcnfernando commented on examples/regexp-type/regexp_type.bal
> +    io:println("Pattern `(?i:BalleRINA)` matches Ballerina ", pattern6.isFullMatch("Ballerina"));
use string:matches() instead

2023-03-21 10:35 UTC, pcnfernando commented on examples/regexp-type/regexp_type.md
> +You can declare `RegExp` variables in two ways either by using the `string` as the module prefix or by using the `regexp` langlib as the module prefix. In the second method, the `regexp` module needs
Defining part should come first. Then the using part
```suggestion
`RegExp` is a built-in type in Ballerina that represents a regular expression. Regular expressions are commonly used for tasks such as validating input, searching and replacing text, and parsing data.

A `RegExp` value can be created by using the regexp template expression or calling the `fromString` method of the [lang.regexp](https://lib.ballerina.io/ballerina/lang.regexp/latest#fromString) module. 
```

2023-03-21 10:40 UTC, pcnfernando commented on examples/regexp-type/regexp_type.out
> +$ bal run regexp_type.bal
Check and update the outputs once the suggestions are addressed

2023-03-23 10:09 UTC, pcnfernando approved these changes

2023-03-24 09:26 UTC, praneesha approved these changes

2023-03-24 09:33 UTC, SasinduDilshara approved these changes

2023-03-24 09:36 UTC, merged