Revamp Function as a Service BBEs
ballerina-platform/ballerina-distribution pull request #4457
Opened 2023-05-23 04:16 UTC by praneesha

## Purpose
Revamp Function as a Service BBEs.

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2023-05-23 06:19 UTC, xlight05 requested changes

2023-07-07 08:39 UTC, praneesha commented on examples/aws-lambda-hello-world/aws-lambda-hello-world.metatags
> +keywords:  ballerina, ballerina by example, bbe, aws lambda
Updated in all FaaS BBEs.

2023-07-07 08:42 UTC, praneesha commented on examples/aws-lambda-hello-world/aws-lambda-hello-world.md
> +>**Tip:** For instructions on getting the values, see [Set up an AWS account](https://ballerina.io/learn/run-in-the-cloud/function-as-a-service/aws-lambda/#set-up-an-aws-account).
Removed from all FaaS BBEs.

2023-07-07 08:43 UTC, praneesha commented on examples/aws-lambda-hello-world/invoke_functions.out
> +{"MESSAGE":"HELLO"}
Added.

2023-07-07 08:44 UTC, praneesha commented on examples/aws-lambda-s3-trigger/aws-lambda-s3-trigger.bal
> +}
Added.

2023-07-07 08:45 UTC, praneesha commented on examples/aws-lambda-execution-context/aws-lambda-execution-context.bal
> +// The `awslambda:Context` object contains request execution context information.
Removed.

2023-07-07 08:46 UTC, praneesha commented on examples/azure-functions-http-trigger/azure-functions-http-trigger.bal
> +}
Added.

2023-07-07 08:47 UTC, praneesha commented on examples/azure-functions-http-trigger/execute_function.out
> +Jack Added to the Queue!
Added.

2023-07-07 09:48 UTC, praneesha commented on examples/aws-lambda-hello-world/aws-lambda-hello-world.bal
> +    log:printInfo(input.toJsonString());
Changed to `io:println.

2023-07-07 09:50 UTC, praneesha commented on examples/azure-functions-hello-world/azure-functions-hello-world.md
> +>**Info:** In the code sample shown above, it has an empty service path and resource path named `hello`. The accessor is `get`. It expects a request with a query parameter for the field `name`. The r
As this info is specific to the BBE will keep it in it.

2023-07-07 09:52 UTC, praneesha commented on examples/azure-functions-http-trigger/az_deploy.out
> +    timer - [timerTrigger]
Removed the Timer trigger part. Will test the outputs of all FaaS BBEs.

2023-07-07 10:01 UTC, praneesha commented on examples/azure-functions-http-trigger/azure-functions-http-trigger.md
> +# Azure Functions- HTTP trigger
We have a simple HTTP trigger scenario in the Azure Functions hello world BBE.

Therefore, renamed this as `HTTP trigger with queue`.

2023-07-07 10:01 UTC, praneesha commented on examples/aws-lambda-s3-trigger/aws-lambda-s3-trigger.md
> +## Invoke the function
Will be addressed in https://github.com/ballerina-platform/ballerina-distribution/pull/4457#discussion_r1201570068.

2023-07-12 12:44 UTC, praneesha commented
Closing as these changes are added in https://github.com/ballerina-platform/ballerina-distribution/pull/4704/f.

2023-07-12 12:44 UTC, closed without merging

2023-07-12 12:44 UTC, praneesha commented on examples/azure-functions-timer-trigger/az_deploy.out
> +    get-hello - [httpTrigger]
Will be addressed in https://github.com/ballerina-platform/ballerina-distribution/pull/4704/f.