Improve I/O BBEs to use new high-level APIs
ballerina-platform/ballerina-distribution pull request #933
Opened 2020-11-13 07:45 UTC by BuddhiWathsala

## Purpose
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/573

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
Use the new high-level IO APIs.

## Related PRs
https://github.com/ballerina-platform/module-ballerina-io/pull/31

## Test environment
- macOS
- Java11
-SLP6

2020-11-19 09:35 UTC, lafernando requested changes
Let's hold this a bit, until we finalize the new BBE structure.

2020-11-24 07:09 UTC, BuddhiWathsala commented
Here only added the File I/O APIs since socket module implementation is not going to use I/O stdlib channel APIs.

2020-11-24 23:05 UTC, lafernando approved these changes

2020-11-25 07:07 UTC, praneesha commented on examples/file-io/file_io.bal
> +    // The content that already read, will write to the given destination file.
```suggestion
    // Write the content is that already read to the given destination file.
```

2020-11-25 07:07 UTC, praneesha commented on examples/file-io/file_io.bal
> +    // Reads the file as a stream of blocks. The default block size is 4KB. Here, the default size is overridden with 2KB.
```suggestion
    // Read the file as a stream of blocks. The default block size is 4KB. Here, the default size is overridden by the value 2KB.
```

2020-11-25 07:07 UTC, praneesha commented on examples/file-io/file_io.bal
> +    // If the file reading was successful, then the content will write to the given destination file using the given stream.
```suggestion
    // If the file reading was successful, then, the content will be written to the given destination file using the given stream.
```

2020-11-25 07:07 UTC, praneesha commented on examples/file-io/file_io.bal
> +    // Reads the file content as a byte array using the given file path.
```suggestion
    // Read the file content as a byte array using the given file path.
```

2020-11-25 07:07 UTC, praneesha commented on examples/file-io/file_io.bal
> +    // Writes the given string to a file.
```suggestion
    // Write the given string to a file.
```

2020-11-25 07:07 UTC, praneesha commented on examples/file-io/file_io.bal
> +    // Writes the given array of lines to a file.
```suggestion
    // Write the given array of lines to a file.
```

2020-11-25 07:07 UTC, praneesha commented on examples/file-io/file_io.bal
> +    // Writes the given stream of lines to a file.
```suggestion
    // Write the given stream of lines to a file.
```

2020-11-25 07:07 UTC, praneesha commented on examples/file-io/file_io.bal
> +    // Initialize JSON file path and content.
```suggestion
    // Initialize the JSON file path and content.
```

2020-11-25 07:07 UTC, praneesha commented on examples/file-io/file_io.bal
> +    // Writes the given JSON to a file.
```suggestion
    // Write the given JSON to a file.
```

2020-11-25 07:07 UTC, praneesha commented on examples/file-io/file_io.bal
> +    // Initialize XML file path and content.
```suggestion
    // Initialize the XML file path and content.
```

2020-11-25 07:07 UTC, praneesha commented on examples/file-io/file_io.bal
> +    // Writes the given XML to a file.
```suggestion
    // Write the given XML to a file.
```

2020-11-25 07:07 UTC, praneesha commented on examples/file-io/file_io.bal
> +    // Initialize CSV file path and content.
```suggestion
    // Initialize the CSV file path and content.
```

2020-11-25 07:07 UTC, praneesha commented on examples/file-io/file_io.bal
> +    // Writes the given content string[][] to a CSV file.
```suggestion
    // Write the given content string[][] to a CSV file.
```

2020-11-25 07:07 UTC, praneesha commented on examples/file-io/file_io.bal
> +    // Writes the given content stream to a CSV file.
```suggestion
    // Write the given content stream to a CSV file.
```

2020-11-25 07:07 UTC, praneesha commented on examples/file-io/file_io.bal
> +    // If the write operation was successful, then perform a read operation to read the CSV content as a stream.
```suggestion
    // If the write operation was successful, then, perform a read operation to read the CSV content as a stream.
```

2020-11-25 07:07 UTC, praneesha commented on examples/file-io/file_io.bal
> +    // If the write operation was successful, then perform a read operation to read the CSV content as a string array of arrays.
```suggestion
    // If the write operation was successful, then, perform a read operation to read the CSV content as a string array of arrays.
```

2020-11-25 07:07 UTC, praneesha commented on examples/file-io/file_io.bal
> +    // If the write operation was successful, then perform a read operation to read the XML content.
```suggestion
    // If the write operation was successful, then, perform a read operation to read the XML content.
```

2020-11-25 07:07 UTC, praneesha commented on examples/file-io/file_io.bal
> +    // If the write operation was successful, then perform a read operation to read the JSON content.
```suggestion
    // If the write operation was successful, then, perform a read operation to read the JSON content.
```

2020-11-25 07:07 UTC, praneesha commented on examples/file-io/file_io.bal
> +    // If the write operation was successful, then perform a read operation to read the lines as a stream.
```suggestion
    // If the write operation was successful, then, perform a read operation to read the lines as a stream.
```

2020-11-25 07:07 UTC, praneesha commented on examples/file-io/file_io.bal
> +    // If the write operation was successful, then perform a read operation to read the lines as an array.
```suggestion
    // If the write operation was successful, then, perform a read operation to read the lines as an array.
```

2020-11-25 07:07 UTC, praneesha commented on examples/file-io/file_io.bal
> +    // If the write operation was successful, then read the content as a string.
```suggestion
    // If the write operation was successful, then, read the content as a string.
```

2020-11-25 07:09 UTC, praneesha commented on examples/file-io/file_io.description
> +// This example demonstrates how bytes can be read and written through the I/O APIs.<br/><br/>
```suggestion
// This example demonstrates how bytes can be read and written using the I/O APIs.<br/><br/>
```

2020-11-25 07:09 UTC, praneesha commented on examples/file-io/file_io.out
> +# Note that, to run this examples successfully you should place an image in the file directory as follow.
```suggestion
# Note that to run this examples successfully, you should place an image in the `files` directory as follows.
```

2020-11-25 09:54 UTC, merged